"""MRI Dataloader logic for aligning clinical visits with MRI files.

This module ensures strict temporal alignment by only pairing
the current visit's target labels with the MRI from that EXACT visit.
"""
from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

from cerebro_x.data.schemas import Oasis2Columns, PairColumns

logger = logging.getLogger(__name__)

def align_pairs_with_mri(
    pairs_df: pd.DataFrame, 
    raw_df: pd.DataFrame, 
    mri_dir: Path | str
) -> pd.DataFrame:
    """
    Aligns longitudinal clinical pairs with their corresponding raw MRI file paths.
    
    Args:
        pairs_df: DataFrame generated by build_next_visit_pairs().
        raw_df: Original OASIS-2 DataFrame containing MRI_ID.
        mri_dir: Path to the directory containing raw MRI .nii.gz files.
        
    Returns:
        pd.DataFrame: A new DataFrame containing subject_id, target_cdr, 
                      and the absolute path to the MRI file.
    """
    mri_dir = Path(mri_dir)
    
    # We need to map (Subject ID, Visit) -> MRI ID
    # Ensure raw_df has required columns
    if Oasis2Columns.SUBJECT_ID not in raw_df.columns or Oasis2Columns.MRI_ID not in raw_df.columns:
        raise ValueError("raw_df must contain Subject ID and MRI ID columns.")
        
    mri_map = {}
    for _, row in raw_df.iterrows():
        sid = row[Oasis2Columns.SUBJECT_ID]
        visit = int(row[Oasis2Columns.VISIT])
        mri_id = row[Oasis2Columns.MRI_ID]
        mri_map[(sid, visit)] = mri_id
        
    aligned_records = []
    missing_count = 0
    
    for _, row in pairs_df.iterrows():
        sid = row[PairColumns.SUBJECT_ID]
        visit = int(row[PairColumns.CURRENT_VISIT])
        target_cdr = float(row[PairColumns.NEXT_CDR])
        
        mri_id = mri_map.get((sid, visit))
        if not mri_id:
            logger.warning(f"No MRI ID found in raw data for Subject {sid} Visit {visit}")
            missing_count += 1
            continue
            
        mri_path = mri_dir / f"{mri_id}.nii.gz"
        
        # We don't verify if mri_path exists here, because on Kaggle it might be mounted later.
        # But we build the struct
        aligned_records.append({
            "subject_id": sid,
            "visit": visit,
            "mri_id": mri_id,
            "mri_path": str(mri_path),
            "next_cdr": target_cdr
        })
        
    aligned_df = pd.DataFrame(aligned_records)
    
    logger.info(f"Aligned {len(aligned_df)} MRI pairs. Missing mapping for {missing_count} pairs.")
    return aligned_df
